day59/BMS/BMS/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include(('book.urls', 'book'), namespace='book')),
    url(r'', include(('account.urls', 'account'), namespace='account')),

]

day59/BMS/book/urls.py
#!usr/bin/env python
# *- coding:utf-8 -*-
# Andy Create @ 9/28/2019 3:34 PM
from django.conf.urls import url
from .views import *

urlpatterns = [
    url(r'book_show/', book_show, name='book_show'),
    url(r'book_add/', book_add, name='book_add'),
    url(r'book_del/(?P<id>\d+)/', book_del, name='book_del'),
    url(r'book_edit/(?P<id>\d+)/', book_edit, name='book_edit'),
    url(r'authordetail_show/', author_detail_show, name='author_detail_show'),
    url(r'authordetail_add/', author_detail_add, name='author_detail_add'),
    url(r'authordetail_edit/(?P<id>\d+)', author_detail_edit, name='author_detail_edit'),
    url(r'authordetail_del/(?P<id>\d+)', author_detail_del, name='author_detail_del'),
    url(r'author_show/', author_show, name='author_show'),
    url(r'author_add/', author_add, name='author_add'),
    url(r'author_edit/(?P<id>\d+)', author_edit, name='author_edit'),
    url(r'author_del/(?P<id>\d+)', author_del, name='author_del'),
    url(r'press_show/', press_show, name='press_show'),
    url(r'press_add/', press_add, name='press_add'),
    url(r'press_edit/(?P<id>\d+)', press_edit, name='press_edit'),
    url(r'press_del/(?P<id>\d+)', press_del, name='press_del'),
]

day59/BMS/templates/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% block title %}
        <title>Book Manage System</title>
    {% endblock title %}
</head>
<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
<link rel="stylesheet" href="{% static 'css/sweetalert.css' %}">
{% block custom_css %}
{% endblock custom_css %}
<body>
<nav class="navbar navbar-inverse  navbar-fixed-top">
    <div class="container">
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                <li><a href="{% url 'book:book_show' %}">Home</a></li>
            </ul>
            <ul class="nav navbar-nav">
                <li><a href="{% url 'book:author_show' %}">作者</a></li>
            </ul>
            <ul class="nav navbar-nav">
                <li><a href="{% url 'book:author_detail_show' %}">作者信息</a></li>
            </ul>
            <ul class="nav navbar-nav">
                <li><a href="{% url 'book:press_show' %}">出版社</a></li>
            </ul>
        </div><!-- /.navbar-collapse -->
    </div>
</nav>
<div class="container">
    <div class="row tip text-center">
        {% block tips %}
            <h3>Welcome to BMS</h3>
        {% endblock tips %}
    </div>
    {% block content %}

    {% endblock content %}

</div>
</body>
<script type="text/javascript" src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
<script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
<script type="text/javascript" src="{% static 'js/sweetalert.min.js' %}"></script>
{% block custom_js %}
{% endblock custom_js %}
</html>