myCRM/myCRM/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include(('sales.urls', 'sales'), namespace='sales')),
    url(r'', include(('rbac.urls', 'rbac'), namespace='rbac')),
]

myCRM/rbac/urls.py
#!usr/bin/env python
# *- coding:utf-8 -*-
# Andy Create @ 10/30/2019 3:52 PM
from django.conf.urls import url, include
from rbac import views

urlpatterns = [
    # 角色管理
    url(r'^role/list/', views.role_list, name='role_list'),  # /rbac/customer/
    url(r'^role/add/', views.role_add_edit, name='role_add'),  # /rbac/customer/
    url(r'^role/edit/(?P<id>\d+)/', views.role_add_edit, name='role_edit'),  # /rbac/customer/
    url(r'^role/del/(?P<id>\d+)/', views.role_del, name='role_del'),  # /rbac/customer/

    # 菜单管理
    url(r'^menu/list/', views.menu_list, name='menu_list'),
    url(r'^menu/add/', views.menu_add_edit, name='menu_add'),
    url(r'^menu/edit/(?P<id>\d+)/', views.menu_add_edit, name='menu_edit'),
    url(r'^menu/del/(?P<id>\d+)/', views.menu_del, name='menu_del'),

    url(r'^permission/add/$', views.permission, name='permission_add'),
    url(r'^permission/edit/(?P<id>\d+)/$', views.permission, name='permission_edit'),
    url(r'^permission/del/(?P<id>\d+)/$', views.del_permission, name='permission_del'),

    url(r'^permissions/list/$', views.multi_permissions, name='permissions_list'),
    url(r'^permissions/dispatch/$', views.dispatch_permission, name='permissions_dispatch'),

]

myCRM/sales/urls.py
#!usr/bin/env python
# *- coding:utf-8 -*-
# Andy Create @ 10/18/2019 11:14 AM

from django.conf.urls import url
from sales.views import *

urlpatterns = [
    url(r'^login/$', login, name='login'),
    url(r'^logout/$', logout, name='logout'),
    url(r'^register/$', register, name='register'),
    url(r'^home/$', CustomerView.as_view(), name='home'),
    url(r'^customer/$', CustomerView.as_view(), name='customer'),
    url(r'^add_customer/$', add_edit_customer, name='add_customer'),
    url(r'^edit_customer/(?P<pk>\d+)/$', add_edit_customer, name='edit_customer'),
    url(r'^consult_record/$', ConsultRecordView.as_view(), name='consult_record'),
    url(r'^add_consult_record/$', add_edit_consult_record, name='add_consult_record'),
    url(r'^edit_consult_record/(?P<pk>\d+)$', add_edit_consult_record, name='edit_consult_record'),
    url(r'^enrollment/$', EnrollmentView.as_view(), name='enrollment'),
    url(r'^add_enrollment/$', add_edit_enrollment, name='add_enrollment'),
    url(r'^edit_enrollment/(?P<pk>\d+)$', add_edit_enrollment, name='edit_enrollment'),
    url(r'^course_record/$', CourseRecordView.as_view(), name='course_record'),
    url(r'^add_course_record/$', add_edit_course_record, name='add_course_record'),
    url(r'^edit_course_record/(?P<pk>\d+)$', add_edit_course_record, name='edit_course_record'),
    url(r'^study_record/(?P<course_id>\d+)$', StudyRecordView.as_view(), name='study_record'),
    url(r'^add_study_record/$', add_edit_study_record, name='add_study_record'),
    url(r'^edit_study_record/(?P<pk>\d+)$', add_edit_study_record, name='edit_study_record'),
]

myCRM/sales/models.py
from django.db import models
from multiselectfield import MultiSelectField
from django.utils.safestring import mark_safe

from rbac.models import User

# Create your models here.

course_choices = (('LinuxL', 'Linux中高级'),
                  ('PythonFullStack', 'Python高级全栈开发'),)

class_type_choices = (('fulltime', '脱产班',),
                      ('online', '网络班'),
                      ('weekend', '周末班',),)

source_type = (('qq', "qq群"),
               ('referral', "内部转介绍"),
               ('website', "官方网站"),
               ('baidu_ads', "百度推广"),
               ('office_direct', "直接上门"),
               ('WoM', "口碑"),
               ('public_class', "公开课"),
               ('website_luffy', "路飞官网"),
               ('others', "其它"),)

enroll_status_choices = (('signed', "已报名"),
                         ('unregistered', "未报名"),
                         ('studying', '学习中'),
                         ('paid_in_full', "学费已交齐"))

seek_status_choices = (('A', '近期无报名计划'), ('B', '1个月内报名'), ('C', '2周内报名'), ('D', '1周内报名'),
                       ('E', '定金'), ('F', '到班'), ('G', '全款'), ('H', '无效'),)
pay_type_choices = (('deposit', "订金/报名费"),
                    ('tuition', "学费"),
                    ('transfer', "转班"),
                    ('dropout', "退学"),
                    ('refund', "退款"),)

attendance_choices = (('checked', "已签到"),
                      ('vacate', "请假"),
                      ('late', "迟到"),
                      ('absence', "缺勤"),
                      ('leave_early', "早退"),)

score_choices = ((100, 'A+'),
                 (90, 'A'),
                 (85, 'B+'),
                 (80, 'B'),
                 (70, 'B-'),
                 (60, 'C+'),
                 (50, 'C'),
                 (40, 'C-'),
                 (0, ' D'),
                 (-1, 'N/A'),
                 (-100, 'COPY'),
                 (-1000, 'FAIL'),)


class UserInfo(User):
    username = models.CharField(max_length=16, verbose_name='用户名')
    password = models.CharField(max_length=100, verbose_name='密码')
    telephone = models.CharField(max_length=11, verbose_name='电话')
    email = models.EmailField(verbose_name='邮箱')
    is_active = models.BooleanField(default=True, verbose_name='是否离职')  # 当前员工是否还是我的员工，False
    depart = models.ForeignKey('Department', verbose_name='部门', on_delete=models.CASCADE, null=True, blank=True)

    def __str__(self):
        return self.username

    class Meta:
        verbose_name_plural = verbose_name = '用户信息'


class Department(models.Model):
    """
        部门表
    """
    name = models.CharField(max_length=32, verbose_name='部门名')
    count = models.IntegerField(default=0, verbose_name='人数')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = verbose_name = '部门'


class Customer(models.Model):
    """
    客户表（最开始的时候大家都是客户，销售就不停的撩你，你还没交钱就是个客户）
    """
    qq = models.CharField(verbose_name='QQ', max_length=64, unique=True, help_text='QQ号必须唯一')
    qq_name = models.CharField(verbose_name='QQ昵称', max_length=64, blank=True, null=True)  # requierd:False
    name = models.CharField('姓名', max_length=32, blank=True, null=True,
                            help_text='学员报名后，请改为真实姓名')  # 可为空，有些人就不愿意给自己的真实姓名
    sex_type = (('male', '男性'), ('female', '女性'))  #
    sex = models.CharField("性别", choices=sex_type, max_length=16, default='male', blank=True,
                           null=True)  # 存的是male或者female，字符串
    # forms.Choicefield(choices=((),()))  #
    birthday = models.DateField('出生日期', default=None, help_text="格式yyyy-mm-dd", blank=True, null=True)
    phone = models.BigIntegerField('手机号', blank=True, null=True)  # 手机号改成字符串的，不然不好搜索
    # phone = models.CharField('手机号', blank=True, null=True)
    source = models.CharField('客户来源', max_length=64, choices=source_type, default='qq')

    introduce_from = models.ForeignKey('self', verbose_name="转介绍自学员", blank=True, null=True,
                                       on_delete=models.CASCADE)  # self指的就是自己这个表，和下面写法是一样的效果

    # introduce_from = models.ForeignKey('Customer', verbose_name="转介绍自学员", blank=True, null=True,on_delete=models.CASCADE)
    course = MultiSelectField("咨询课程", choices=course_choices)  # 多选，并且存成一个列表的格式,通过modelform来用的时候，会成为一个多选框
    # [kecheng1,kecheng2]
    # course = models.CharField("咨询课程", choices=course_choices) #如果你不想用上面的多选功能，可以使用Charfield来存
    class_type = models.CharField("班级类型", max_length=64, choices=class_type_choices, default='fulltime')
    customer_note = models.TextField("客户备注", blank=True, null=True, )
    status = models.CharField("状态", choices=enroll_status_choices, max_length=64, default="unregistered",
                              help_text="选择客户此时的状态")  # help_text这种参数基本都是针对admin应用里面用的

    date = models.DateTimeField("咨询日期", auto_now_add=True)  # 这个没啥用昂，我问销售，销售说是为了一周年的时候给客户发一个祝福信息啥的
    last_consult_date = models.DateField("最后跟进日期", auto_now_add=True)  # 考核销售的跟进情况，如果多天没有跟进，会影响销售的绩效等
    next_date = models.DateField("预计再次跟进时间", blank=True, null=True)  # 销售自己大概记录一下自己下一次会什么时候跟进，也没啥用

    # 用户表中存放的是自己公司的所有员工。
    consultant = models.ForeignKey('UserInfo', verbose_name="销售", related_name='customers', blank=True, null=True,
                                   on_delete=models.CASCADE)

    # 一个客户可以报多个班，报个脱产班，再报个周末班等，所以是多对多。
    class_list = models.ManyToManyField('ClassList', verbose_name="已报班级", blank=True, )

    # 成单日期，统计成单日期的时候会用到
    deal_date = models.DateField(verbose_name='成单日期', null=True, blank=True)

    # delete_status = models.BooleanField(default=False)
    class Meta:
        ordering = ['id', ]
        verbose_name_plural = verbose_name = '客户信息'

    def __str__(self):
        return self.name + ":" + self.qq


class Campuses(models.Model):
    """
    校区表
    """
    name = models.CharField(verbose_name='校区', max_length=64)
    address = models.CharField(verbose_name='详细地址', max_length=512, blank=True, null=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = verbose_name = '校区'


class ClassList(models.Model):
    """
    班级表
    """
    course = models.CharField("课程名称", max_length=64, choices=course_choices)
    semester = models.IntegerField("学期")  # python20期等
    campuses = models.ForeignKey('Campuses', verbose_name="校区", on_delete=models.CASCADE)
    price = models.IntegerField("学费", default=10000)
    memo = models.CharField('说明', blank=True, null=True, max_length=100)
    start_date = models.DateField("开班日期")
    graduate_date = models.DateField("结业日期", blank=True, null=True)  # 不一定什么时候结业，哈哈，所以可为空

    # contract = models.ForeignKey('ContractTemplate', verbose_name="选择合同模版", blank=True, null=True,on_delete=models.CASCADE)
    teachers = models.ManyToManyField('UserInfo',
                                      verbose_name="老师")  # 对了，还有一点，如果你用的django2版本的，那么外键字段都需要自行写上on_delete=models.CASCADE

    class_type = models.CharField(choices=class_type_choices, max_length=64, verbose_name='班级类型', blank=True, null=True)

    class Meta:
        unique_together = ("course", "semester", 'campuses')
        verbose_name_plural = verbose_name = '班级'

    def __str__(self):
        return "{}{}({})".format(self.get_course_display(), self.semester, self.campuses)


class ConsultRecord(models.Model):
    """
    跟进记录表
    """
    customer = models.ForeignKey('Customer', verbose_name="所咨询客户")
    note = models.TextField(verbose_name="跟进内容...")
    status = models.CharField("跟进状态", max_length=8, choices=seek_status_choices, help_text="选择客户此时的状态")
    consultant = models.ForeignKey("UserInfo", verbose_name="跟进人", related_name='records')
    date = models.DateTimeField("跟进日期", auto_now_add=True)
    delete_status = models.BooleanField(verbose_name='删除状态', default=False)

    def __str__(self):
        return self.customer.name + '<--' + self.consultant.username

    class Meta:
        verbose_name_plural = verbose_name = '跟进记录'


class Enrollment(models.Model):
    """
    报名表
    """
    why_us = models.TextField("为什么报名", max_length=1024, default=None, blank=True, null=True)
    your_expectation = models.TextField("学完想达到的具体期望", max_length=1024, blank=True, null=True)
    # contract_agreed = models.BooleanField("我已认真阅读完培训协议并同意全部协议内容", default=False)
    contract_approved = models.BooleanField("审批通过", help_text="在审阅完学员的资料无误后勾选此项,合同即生效", default=False)
    enrolled_date = models.DateTimeField(auto_now_add=True, verbose_name="报名日期")
    memo = models.TextField('备注', blank=True, null=True)
    delete_status = models.BooleanField(verbose_name='删除状态', default=False)
    customer = models.ForeignKey('Customer', verbose_name='客户名称')
    school = models.ForeignKey('Campuses')
    enrolment_class = models.ForeignKey("ClassList", verbose_name="所报班级")

    class Meta:
        unique_together = ('enrolment_class', 'customer')
        verbose_name_plural = verbose_name = '注册'

    def __str__(self):
        return self.customer.name


class CourseRecord(models.Model):
    """课程记录表"""
    day_num = models.IntegerField("节次", help_text="此处填写第几节课或第几天课程...,必须为数字")
    date = models.DateField(auto_now_add=True, verbose_name="上课日期")
    course_title = models.CharField('本节课程标题', max_length=64, blank=True, null=True)
    course_memo = models.TextField('本节课程内容', max_length=300, blank=True, null=True)
    has_homework = models.BooleanField(default=True, verbose_name="本节有作业")
    homework_title = models.CharField('本节作业标题', max_length=64, blank=True, null=True)
    homework_memo = models.TextField('作业描述', max_length=500, blank=True, null=True)
    scoring_point = models.TextField('得分点', max_length=300, blank=True, null=True)

    re_class = models.ForeignKey('ClassList', verbose_name="班级")
    teacher = models.ForeignKey('UserInfo', verbose_name="讲师")

    class Meta:
        unique_together = ('re_class', 'day_num')
        verbose_name_plural = verbose_name = '课程记录'

    def __str__(self):
        return str(self.day_num)


class StudyRecord(models.Model):
    """
    学习记录
    """

myCRM/templates/customer/add_edit_customer.html
{% extends 'starter.html' %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}编辑客户信息{% endblock title %}</title>
</head>
<body>
{% block page_header %}
        客户信息
        <small>{{ label }}</small>

{% endblock page_header %}
{% block content %}
    <form class="form-horizontal col-sm-offset-1 col-sm-10" method="post">
    {% csrf_token %}
    {% for field in customer_form %}
        <div class="form-group">
            <label for="{{ field.id_for_label }}" class="col-sm-2 control-label">{{ field.label }}</label>
            <div class="col-sm-10">
                {{ field }}
                <span class="text-danger">{{ field.errors.0 }}</span>
            </div>
        </div>

    {% endfor %}
    <input type="submit" class="btn btn-success" value="提交">
{% endblock content %}

</body>
</html>

myCRM/templates/customer/customer.html
{% extends 'starter.html' %}
{% load static %}
{% load customertags %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}客户列表{% endblock title %}</title>
</head>

<body>
{% block page_header %}

        {% if tag == '1' %}
            公户信息

        {% else %}
            我的客户信息
        {% endif %}

{% endblock page_header %}
{% block content %}
    <form action="" class="form-inline pull-right" method="get">

        <div class="form-group">
            <select name="search_field" id="search_field" class="form-control">
                <option value="qq__contains">qq</option>
                <option value="name__contains">姓名</option>
            </select>

            <input type="text" class="form-control" id="" placeholder="请输入" name="keyword"
                   value="{{ keyword|default:'' }}">
        </div>
        <button type="submit" class="btn btn-success">搜索</button>
    </form>
    <a href="{% url 'sales:add_customer' %}">
        <button class="btn btn-success ">添加</button>
    </a>

    <form method="post" action="{% url 'sales:customer' %}" class="form-inline">

        <select name="action" class="form-control">

            {% show_pri_pub_option request %}
            <option value="bulk_delete">批量删除</option>
        </select>
        {% csrf_token %}

        <input type="submit" class="btn btn-primary btn-sm" value="应用">
        <p>{{ error_tip }}</p>
        <table class="table table-bordered table-striped table-hover">
            <!-- On rows -->
            <thead>
            <tr>
                <td class="">
                    <input type="button" class=" btn-success select_id" id="select_all" value="全选">
                </td>
                <td class="success">序号</td>
                <td class="info">qq号</td>
                <td class="success">姓名</td>
                <td class="info">性别</td>
                <td class="success">咨询课程</td>
                <td class="info">状态</td>
                {% ifequal  tag '0' %}
                    <td class="info">跟进记录</td>
                    <td class="success">销售</td>
                {% endifequal %}
                <td class="success">操作</td>
            </tr>
            </thead>
            <tbody>
            {% for customer in all_customers %}
                <tr>
                    <td><input type="checkbox" class="select_pk" name="pk" value="{{ customer.pk }}"></td>
                    <td>{{ forloop.counter }}</td>
                    <td>
                        {{ customer.qq }}
                    </td>
                    <td>{{ customer.name }}</td>
                    <td>{{ customer.get_sex_display }}</td>
                    <td>{{ customer.get_course_display }}</td>
                    <td>{{ customer.get_status_display }}</td>
                    {% ifequal tag '0' %}
                        <td><a href="{% url 'sales:consult_record' %}?customer_id={{ customer.pk }}">跟进详情</a></td>
                        <td>{{ customer.consultant.username }}</td>
                    {% endifequal %}
                    <td>
                        <a class="fa fa-2x fa-edit"
                           href="{% reverse_url 'sales:edit_customer' customer.pk request %}">
                        </a>
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </form>
{% endblock %}
</body>

</html>
{% block paginator %}
    {{ page_html }}
{% endblock paginator %}

{% block custom_js %}
    <script>
        $(document).ready(function () {
            var field = '{{ search_field }}';  // 'name__contains'
            $('#search_field').val(field);
            $("#select_all").click(function () {
                $(".select_pk").attr('checked', true);
            })
        })
    </script>
{% endblock custom_js %}