day59/BMS/BMS/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include(('book.urls', 'book'), namespace='book')),
    url(r'', include(('account.urls', 'account'), namespace='account')),

]

day59/BMS/book/urls.py
#!usr/bin/env python
# *- coding:utf-8 -*-
# Andy Create @ 9/28/2019 3:34 PM
from django.conf.urls import url
from .views import *

urlpatterns = [
    url(r'book_show/', book_show, name='book_show'),
    url(r'book_add/', book_add, name='book_add'),
    url(r'book_del/(?P<id>\d+)/', book_del, name='book_del'),
    url(r'book_edit/(?P<id>\d+)/', book_edit, name='book_edit'),
    url(r'authordetail_show/', author_detail_show, name='author_detail_show'),
    url(r'authordetail_add/', author_detail_add, name='author_detail_add'),
    url(r'authordetail_edit/(?P<id>\d+)', author_detail_edit, name='author_detail_edit'),
    url(r'authordetail_del/(?P<id>\d+)', author_detail_del, name='author_detail_del'),
    url(r'author_show/', author_show, name='author_show'),
    url(r'author_add/', author_add, name='author_add'),
    url(r'author_edit/(?P<id>\d+)', author_edit, name='author_edit'),
    url(r'author_del/(?P<id>\d+)', author_del, name='author_del'),
    url(r'press_show/', press_show, name='press_show'),
    url(r'press_add/', press_add, name='press_add'),
    url(r'press_edit/(?P<id>\d+)', press_edit, name='press_edit'),
    url(r'press_del/(?P<id>\d+)', press_del, name='press_del'),
]

day59/BMS/book/models.py
from django.db import models
from django.utils import timezone


# Create your models here.


class Author(models.Model):
    # 作者
    name = models.CharField(verbose_name='姓名', max_length=32)
    age = models.IntegerField(verbose_name='年龄')
    author_detail = models.OneToOneField(to="AuthorDetail", verbose_name='作者详情')

    class Meta:
        verbose_name_plural = verbose_name = '作者'

    def __str__(self):
        return self.name


class AuthorDetail(models.Model):
    # 作者详情
    birthday = models.DateField(verbose_name='生日')
    telephone = models.CharField(verbose_name='电话', max_length=11)
    addr = models.CharField(verbose_name='地址', max_length=64)

    class Meta:
        verbose_name_plural = verbose_name = '作者详情'

    def __str__(self):
        return 'Ta生于{0}年{1}月{2}'.format(self.birthday.year, self.birthday.month, self.birthday.day)


class Press(models.Model):
    # 出版社
    name = models.CharField(verbose_name='社名', max_length=32)
    city = models.CharField(verbose_name='所在城市', max_length=32)

    class Meta:
        verbose_name_plural = verbose_name = '出版社'

    def __str__(self):
        return self.name


class Book(models.Model):
    # 书籍
    name = models.CharField(verbose_name='书名', max_length=20, )
    price = models.DecimalField(
        verbose_name='价格', max_digits=5, decimal_places=2)
    publish_date = models.DateField(verbose_name='出版日期', default=timezone.now)
    press = models.ForeignKey(to='Press', verbose_name='出版社', related_name='press_book')
    author = models.ManyToManyField(to='Author', verbose_name='作者', related_name='author_book')

    class Meta:
        verbose_name_plural = verbose_name = '书籍'

    def __str__(self):
        return self.name

day59/BMS/book/forms.py
#!usr/bin/env python
# *- coding:utf-8 -*-
# Andy Create @ 10/7/2019 3:03 PM

from django import forms
from book.models import *


class AuthorDetailForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(AuthorDetailForm, self).__init__(*args, **kwargs)
        for field in iter(self.fields):
            self.fields[field].widget.attrs.update({'class': 'form-control'})

    class Meta:
        model = AuthorDetail
        fields = "__all__"
        widgets = {
            'birthday': forms.TextInput(attrs={'type': 'date'}),
        }


class AuthorForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(AuthorForm, self).__init__(*args, **kwargs)
        for field in iter(self.fields):
            self.fields[field].widget.attrs.update({'class': 'form-control', })

    class Meta:
        model = Author
        fields = '__all__'


class BookForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(BookForm, self).__init__(*args, **kwargs)
        for field in iter(self.fields):
            self.fields[field].widget.attrs.update({'class': 'form-control'})

    class Meta:
        model = Book
        fields = '__all__'

        widgets = {
            'publish_date': forms.TextInput(attrs={'type': 'date'}),
        }


class PressForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(PressForm, self).__init__(*args, **kwargs)
        for field in iter(self.fields):
            self.fields[field].widget.attrs.update({'class': 'form-control'})

    class Meta:
        model = Press
        fields = "__all__"

day59/BMS/book/views.py
from django.shortcuts import render, redirect
from django.db.models import Count
from django.http import JsonResponse
from .models import *
from book.forms import *


# Create your views here.
def author_detail_add(request):
    # 添加作者详情
    if request.method == 'GET':
        author_detail_form = AuthorDetailForm()
        context = {
            'author_detail_form': author_detail_form,
        }
        return render(request, 'book/author_detail_add.html', context)
    else:
        added_author_detail = AuthorDetailForm(request.POST)
        if added_author_detail.is_valid():
            added_author_detail.save()
        else:
            context = {
                'author_detail_form': added_author_detail,
            }
            return render(request, 'book/author_detail_add.html', context)
        return redirect('book:author_detail_show')


def author_detail_show(request):
    # 展示作者详情
    authordetails = AuthorDetail.objects.all()
    context = {
        'authordetails': authordetails,
    }
    return render(request, 'book/author_detail_show.html', context)


def author_detail_edit(request, id):
    # 编辑作者详情
    author_detail = AuthorDetail.objects.get(id=id)
    if request.method == 'GET':
        edit_author_detail = AuthorDetailForm(instance=author_detail)
        context = {
            'author_detail_form': edit_author_detail,
            'author_detail': author_detail,
        }
        return render(request, 'book/author_detail_edit.html', context)
    else:
        updated_author_detail_form = AuthorDetailForm(request.POST, instance=author_detail)
        if updated_author_detail_form.is_valid():
            updated_author_detail_form.save()
            return redirect('book:author_detail_show')
        else:
            context = {
                'author_detail_form': updated_author_detail_form,
                'author_detail': author_detail,
            }
            return render(request, 'book/author_detail_edit.html', context)


def author_detail_del(request, id):
    # 删除作者详情
    author_detail = AuthorDetail.objects.get(id=id)
    author_detail.delete()
    return redirect('book:author_detail_show')


def author_show(request):
    # 展示所有作者
    authors = Author.objects.all()
    context = {
        'authors': authors,
    }
    return render(request, 'book/author_show.html', context)


def author_add(request):
    # 添加作者
    # TODO, 处理当作者详情冲突时的情况
    # TODO, 添加完作者怎么保存已经填写的姓名，年龄信息，并填充到作者添加页面

    # 传入所有的作者详情，供选择
    authordetails = AuthorDetail.objects.all()

    if request.method == 'GET':
        authors = Author.objects.all()

        context = {
            'authors': authors,
            'authordetails': authordetails,
        }
        return render(request, 'book/author_add.html', context)
    else:
        name = request.POST.get('name')
        age = request.POST.get('age')
        author_detail_id = request.POST.get('authordetail')
        new_author_detail = AuthorDetail.objects.get(id=author_detail_id)
        new_author, _ = Author.objects.update_or_create(name=name, age=age, author_detail=new_author_detail)
        return redirect('book:author_show')


def author_edit(request, id):
    # 编辑作者
    author = Author.objects.get(id=id)
    if request.method == 'GET':
        author_form = AuthorForm(instance=author)
        context = {
            'author_form': author_form,
            'author': author,
        }
        return render(request, 'book/author_edit.html', context)
    else:
        updated_author = AuthorForm(request.POST, instance=author)
        if updated_author.is_valid():
            updated_author.save()
        else:
            context = {
                'author': author,
                'author_form': updated_author,
            }
            return render(request, 'book/author_edit.html', context)
        return redirect('book:author_show')


def author_del(request, id):
    # 删除作者
    author = Author.objects.get(id=id)
    author.delete()
    return redirect('book:author_show')


def press_show(request):
    press_list = Press.objects.annotate(book_count=Count('press_book'))
    context = {
        'press_list': press_list,
    }

    return render(request, 'book/press_show.html', context)


def press_edit(request, id):
    press = Press.objects.get(id=id)
    if request.method == 'GET':
        press_form = PressForm(instance=press)
        context = {
            'press_form': press_form,
            'press': press,
        }
        return render(request, 'book/press_edit.html', context)
    else:
        updated_press = PressForm(request.POST, instance=press)
        if updated_press.is_valid():
            press.save()
        else:
            context = {
                'press': press,
                'press_form': updated_press,
            }
            return render(request, 'book/press_edit.html', context)
        return redirect('book:press_show')


def press_del(request, id):
    press = Press.objects.get(id=id)
    press.delete()
    return redirect('book:press_show')


def press_add(request):
    # 添加出版社
    if request.method == 'GET':
        press_form = PressForm()
        context = {
            'press_form': press_form,
        }
        return render(request, 'book/press_add.html', context)
    else:
        name = request.POST.get('name')
        city = request.POST.get('city')
        new_press, _ = Press.objects.update_or_create(name=name, city=city)
        return redirect('book:press_show')


def book_show(request):
    # 展示所有书籍
    books = Book.objects.all()
    context = {
        'books': books,
    }
    return render(request, 'book/book_show.html', context)


def book_add(request):
    # 添加书籍
    if request.method == 'GET':
        book_form = BookForm()
        context = {
            'book_form': book_form,
        }
        # authors = Author.objects.all()
        # press_list = Press.objects.all()
        # context = {
        #     'authors': authors,
        #     'press_list': press_list,
        # }
        return render(request, 'book/book_add.html', context)

    else:
        name = request.POST.get('name')
        price = request.POST.get('price')
        publish_date = request.POST.get('publish_date')

        press_id = request.POST.get('press')  # 出版社id
        press_obj = Press.objects.get(id=int(press_id))  # 出版社对象
        new_book, _ = Book.objects.update_or_create(
            name=name,
            price=price,
            publish_date=publish_date,
            press=press_obj,
        )
        # 获取作者列表的 id列表
        author_list = request.POST.getlist('author')
        new_book.author.add(*author_list)  # 添加作者， 星星打散
        return redirect('book:book_show')


def book_del(request, id):
    # 删除书籍
    book = Book.objects.get(pk=id)
    if book:
        book.delete()
        data = {'status': 1}
    else:
        data = {'status': 0}

    return JsonResponse(data)


def book_edit(request, id):
    # # 编辑书籍
    book = Book.objects.get(id=id)
    if request.method == 'GET':
        book_obj = BookForm(instance=book)
        context = {
            'book_obj': book_obj,
            'book': book,
        }
        return render(request, 'book/book_edit.html', context)
    else:
        updated_book = BookForm(request.POST, instance=book)
        if updated_book.is_valid():
            updated_book.save()
        else:
            context = {
                'book_obj': updated_book,
                'book': book,
            }
            return render(request, 'book/book_edit.html', context)
        return redirect('book:book_show')

day59/BMS/templates/book/author_add.html
{% extends 'base.html' %}


{% block tips %}
    <h3>添加作者</h3>
{% endblock tips %}


{% block content %}

    <div class=" col-md-offset-1 col-md-10">
        <a href="{% url 'book:author_show' %}">
            <button type="button" class="btn btn-primary">作者列表</button>
        </a>
        <form action="{% url 'book:author_add' %}" method="post">
            {% csrf_token %}
            <div class="form-group">
                <label for="name">作者姓名</label>
                <input type="text" class="form-control" id="name" name="name" placeholder="名字">
            </div>
            <div class="form-group">
                <label for="age">年龄</label>
                <input type="number" class="form-control" id="age" name="age" placeholder="年龄">
            </div>
            <div class="form-group">
                <p><label for="authordetail">作者详情</label></p>
                <select name="authordetail">
                    {% for detail in authordetails %}
                        <option value="{{ detail.id }}" {% ifequal select_id detail.id %}
                                selected=selected {% endifequal %}>{{ detail }}</option>
                    {% endfor %}
                </select>
                <a href="{% url 'book:author_detail_add' %}">
                    <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
                </a>
            </div>
            <button type="submit" class="btn btn-success pull-right">添加</button>
        </form>
    </div>

{% endblock content %}

day59/BMS/templates/book/author_detail_add.html
{% extends 'base.html' %}


{% block tips %}
    <h3>添加作者详情</h3>
{% endblock tips %}


{% block content %}
    <div class="col-md-offset-2 col-md-6">
        <form action="{% url 'book:author_detail_add' %}" method="post">

            {% csrf_token %}
            {% for field in author_detail_form %}
                <div class="form-group">
                    {{ field.label }}
                    {{ field }}
                    <span class="text-danger">{{ field.errors.0 }}</span>
                </div>
            {% endfor %}
            <button type="submit" class="btn btn-success pull-right">提交</button>
        </form>
    </div>
{% endblock content %}

day59/BMS/templates/book/author_detail_edit.html
{% extends 'base.html' %}


{% block tips %}
    <h3>编辑作者信息</h3>
{% endblock tips %}


{% block content %}
    <div class="col-md-offset-2 col-md-6">
        <a href="{% url 'book:author_detail_show' %}">
            <button type="button" class="btn btn-primary">展示作者详情</button>
        </a>
        <form action="{% url 'book:author_detail_edit' author_detail.id %}" method="post">
            {% csrf_token %}
            {% for field in author_detail_form %}
                <div class="form-group">
                    {{ field.label }}
                    {{ field }}
                    <span class="text-danger">{{ field.errors.0 }}</span>
                </div>
            {% endfor %}
            <button type="submit" class="btn btn-success pull-right">提交</button>
        </form>
    </div>
{% endblock content %}

day59/BMS/templates/book/author_detail_show.html
{% extends 'base.html' %}

{% block tips %}
    <h3>作者详情管理</h3>
{% endblock tips %}


{% block content %}
    <div class="col-md-offset-1 col-md-10">
        <p class="">
            <a href="{% url 'book:author_detail_add' %}">
                <button type="button" class="btn btn-primary">添加作者详情</button>
            </a>
        </p>
        <p>
        <p>
        <h3 class="text-center">作者详情列表</h3>
        </p>
        <table class="table table-bordered table-striped table-hover">
            <!-- On rows -->
            <thead>
            <tr>
                <td class="success">编号</td>
                <td class="info">姓名</td>
                <td class="info">生日</td>
                <td class="success">电话</td>
                <td class="info">地址</td>
                <td class="success">操作</td>
            </tr>
            </thead>
            <tbody>
            {% for authordetail in authordetails %}
                <tr>
                    <td>{{ forloop.counter }}</td>
                    <td>{{ authordetail.author.name }}</td>
                    <td>{{ authordetail.birthday|date:'Y-m-d' }}</td>
                    <td>{{ authordetail.telephone }}
                    </td>
                    <td>{{ authordetail.addr }}</td>
                    <td>
                        <button type="button" class="btn btn-warning"><a
                                href="{% url 'book:author_detail_edit' authordetail.id %}">编辑</a>
                        </button>
                        <button type="button" class="btn btn-danger"><a
                                href="{% url 'book:author_detail_del' authordetail.id %}">删除</a>
                        </button>
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>

    </div>
{% endblock content %}

day59/BMS/templates/book/author_edit.html
{% extends 'base.html' %}


{% block tips %}
    <h3>编辑作者信息</h3>
{% endblock tips %}


{% block content %}
    <div class="col-md-offset-2 col-md-6">
        <a href="{% url 'book:author_show' %}">
            <button type="button" class="btn btn-primary">展示作者</button>
        </a>
        <form action="{% url 'book:author_edit' author.id %}" method="post">
            {% csrf_token %}
            {% for field in author_form %}
                <div class="form-group">
                    {{ field.label }}
                    {{ field }}
                    <span class="text-danger">{{ field.errors.0 }}</span>
                </div>
            {% endfor %}
            <button type="submit" class="btn btn-success pull-right">提交</button>
        </form>
    </div>
{% endblock content %}

day59/BMS/templates/book/author_show.html
{% extends 'base.html' %}
{% block tips %}
    <h3>作者管理</h3>
{% endblock tips %}
{% block content %}
    <div class="col-md-offset-1 col-md-10">
        <a href="{% url 'book:author_add' %}">
            <button type="button" class="btn btn-primary">添加作者</button>
        </a>
        <p>
        <h3 class="text-center">作者列表</h3>
        </p>
        <table class="table table-bordered table-striped table-hover">
            <!-- On rows -->
            <thead>
            <tr>
                <td class="success">编号</td>
                <td class="info">姓名</td>
                <td class="success">年龄</td>
                <td class="info">出生日期</td>
                <td class="success">电话</td>
                <td class="info">地址</td>
                <td class="success">操作</td>
            </tr>
            </thead>
            <tbody>
            {% for author in authors %}
                <tr>
                    <td>{{ forloop.counter }}</td>
                    <td>{{ author.name }}</td>
                    <td>{{ author.age }}
                    </td>
                    <td>{{ author.author_detail.birthday|date:"Y-m-d" }}</td>
                    <td>{{ author.author_detail.telephone }}</td>
                    <td>{{ author.author_detail.addr }}</td>
                    <td>
                        <button type="button" class="btn btn-warning"><a
                                href="{% url 'book:author_edit' author.id %}">编辑</a>
                        </button>
                        <button type="button" class="btn btn-danger"><a
                                href="{% url 'book:author_del' author.id %}">删除</a>
                        </button>
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>

{% endblock content %}

day59/BMS/templates/book/book_add.html
{% extends 'base.html' %}


{% block tips %}
    <h3>添加书籍</h3>
{% endblock tips %}

{% block content %}
    <div class="col-md-offset-2 col-md-6">
        <form action="{% url 'book:book_add' %}" method="post">
            {% csrf_token %}
            {% for field in book_form %}
                {{ field.label }}
                {{ field }}
                <span class="text-danger">{{ field.errors.0 }}</span>
            {% endfor %}
            <button type="submit" class="btn btn-success pull-right">提交</button>
        </form>
    </div>
{% endblock content %}

day59/BMS/templates/book/book_edit.html
{% extends 'base.html' %}


{% block tips %}
    <h3>编辑书籍信息</h3>
{% endblock tips %}

{% block content %}
    <div class="container">
        <form class="col-md-offset-2 col-md-6" action="{% url 'book:book_edit' book.id %}" method="post">
            {% csrf_token %}
            {% for field in book_obj %}
                <div class="form-group">
                    {{ field.label }}
                    {{ field }}
                    <span class="text-danger">{{ field.errors.0 }}</span>
                </div>
            {% endfor %}
            <div class="col-md-12">
                <button type="submit" class="btn btn-success pull-right">提交</button>
            </div>
        </form>
    </div>
{% endblock content %}

day59/BMS/templates/book/book_show.html
{% extends 'base.html' %}
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% block title %}
        <title>Book Manage System</title>
    {% endblock title %}
</head>
{% block custom_css %}
    <link rel="stylesheet" href="{% static 'css/book.css' %}">
{% endblock custom_css %}

{% block tips %}
    <h3>Welcome to BMS</h3>
{% endblock tips %}

{% block content %}
    <div class="col-md-12">
        <p class="">
            <a href="{% url 'book:book_add' %}">
                <button type="button" class="btn btn-primary">添加书籍</button>
            </a>
        </p>
        <p>
        <h3 class="text-center">图书列表</h3>
        </p>
        <table class="table table-bordered table-striped table-hover">
            <!-- On rows -->
            <thead>
            <tr>
                <td class="success">编号</td>
                <td class="info">书籍名称</td>
                <td class="success">作者</td>
                <td class="info">价格</td>
                <td class="success">出版日期</td>
                <td class="info">出版社</td>
                <td class="success">操作</td>
            </tr>
            </thead>
            <tbody>
            {% csrf_token %}
            {% for book in books %}
                <tr>
                    <td>{{ forloop.counter }}</td>
                    <td>{{ book.name }}</td>
                    <td>{% for author in book.author.all %}
                        {{ author }}
                        {% if not forloop.last %},
                        {% endif %}
                    {% endfor %}
                    </td>
                    <td>{{ book.price }}</td>
                    <td>{{ book.publish_date|date:"Y-m-d" }}</td>
                    <td>{{ book.press }}</td>
                    <td>
                        <button type="button" class="btn btn-warning"><a
                                href="{% url 'book:book_edit' book.id %}">编辑</a>
                        </button>
                        <button type="button" class="btn btn-danger btn-del" value="{{ book.id }}">删除
                        </button>
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>

    </div>

{% endblock content %}

{% block custom_js %}
    <script>
        $(".btn-danger").on("click", function () {
            var the = $(this);
            var deleteId = the.attr("value");

            swal({
                    title: "你确定要删除吗？",
                    text: "删除可就找不回来了哦！",
                    type: "warning",
                    showCancelButton: true,
                    confirmButtonClass: "btn-danger",
                    confirmButtonText: "删除",
                    cancelButtonText: "取消",
                    closeOnConfirm: false
                },
                function () {

                    $.ajax({
                        url: "/book_del/" + deleteId + '/',
                        type: "post",
                        data: {
                            "id": deleteId, 'csrfmiddlewaretoken': '{{ csrf_token }}',
                        },
                        success: function (data) {
                            if (data.status === 1) {
                                swal("删除成功!", "你可以准备跑路了！", "success");
                                the.parent().parent().remove();
                            } else {
                                swal("删除失败", "你可以再尝试一下！", "error")
                            }
                        }
                    })
                });
        })
    </script>
{% endblock custom_js %}
</html>

day59/BMS/templates/book/press_add.html
{% extends 'base.html' %}


{% block tips %}
    <h3>添加出版社</h3>
{% endblock tips %}


{% block content %}
    <div class="col-md-offset-2 col-md-6">
        <form action="{% url 'book:press_add' %}" method="post">
            {% csrf_token %}
            {% for field in press_form %}

                <div class="form-group">
                    {{ field.label }}
                    {{ field }}
                    <span class="text-danger">{{ field.errors.0 }}</span>
                </div>
            {% endfor %}
            <button type="submit" class="btn btn-success pull-right">提交</button>
        </form>
    </div>
{% endblock content %}

day59/BMS/templates/book/press_edit.html
{% extends 'base.html' %}


{% block tips %}
    <h3>编辑出版社信息</h3>
{% endblock tips %}


{% block content %}
    <div class="col-md-offset-2 col-md-6">
        <a href="{% url 'book:press_show' %}">
            <button type="button" class="btn btn-primary">展示出版社</button>
        </a>
        <form action="{% url 'book:press_edit' press.id %}" method="post">
            {% csrf_token %}

            {% for field in press_form %}
                {{ field.label }}
                {{ field }}
                <span class="text-danger">{{ field.errors.0 }}</span>
            {% endfor %}
            <button type="submit" class="btn btn-success pull-right">提交</button>
        </form>
    </div>
{% endblock content %}

day59/BMS/templates/book/press_show.html
{% extends 'base.html' %}
{% block tips %}
    <h3>出版社管理</h3>
{% endblock tips %}
{% block content %}
    <div class="col-md-offset-1 col-md-10">
        <a href="{% url 'book:press_add' %}">
            <button type="button" class="btn btn-primary">添加出版社</button>
        </a>
        <p>
        <p>
        <h3 class="text-center">出版社列表</h3></p>
        <table class="table table-bordered table-striped table-hover">
            <!-- On rows -->
            <thead>
            <tr>
                <td class="success">编号</td>
                <td class="info">出版社名</td>
                <td class="success">所在城市</td>
                <td class="info">出版书数量</td>
                <td class="success">操作</td>
            </tr>
            </thead>
            <tbody>
            {% for press in press_list %}
                <tr>
                    <td>{{ forloop.counter }}</td>
                    <td>{{ press.name }}</td>
                    <td>{{ press.city }}
                    </td>
                    <td>{{ press.book_count }}</td>
                    <td>
                        <button type="button" class="btn btn-warning"><a
                                href="{% url 'book:press_edit' press.id %}">编辑</a>
                        </button>
                        <button type="button" class="btn btn-danger"><a
                                href="{% url 'book:press_del' press.id %}">删除</a>
                        </button>
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock content %}