myCRM/myCRM/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include(('sales.urls', 'sales'), namespace='sales')),
    url(r'', include(('rbac.urls', 'rbac'), namespace='rbac')),
]

myCRM/rbac/urls.py
#!usr/bin/env python
# *- coding:utf-8 -*-
# Andy Create @ 10/30/2019 3:52 PM
from django.conf.urls import url, include
from rbac import views

urlpatterns = [
    # 角色管理
    url(r'^role/list/', views.role_list, name='role_list'),  # /rbac/customer/
    url(r'^role/add/', views.role_add_edit, name='role_add'),  # /rbac/customer/
    url(r'^role/edit/(?P<id>\d+)/', views.role_add_edit, name='role_edit'),  # /rbac/customer/
    url(r'^role/del/(?P<id>\d+)/', views.role_del, name='role_del'),  # /rbac/customer/

    # 菜单管理
    url(r'^menu/list/', views.menu_list, name='menu_list'),
    url(r'^menu/add/', views.menu_add_edit, name='menu_add'),
    url(r'^menu/edit/(?P<id>\d+)/', views.menu_add_edit, name='menu_edit'),
    url(r'^menu/del/(?P<id>\d+)/', views.menu_del, name='menu_del'),

    url(r'^permission/add/$', views.permission, name='permission_add'),
    url(r'^permission/edit/(?P<id>\d+)/$', views.permission, name='permission_edit'),
    url(r'^permission/del/(?P<id>\d+)/$', views.del_permission, name='permission_del'),

    url(r'^permissions/list/$', views.multi_permissions, name='permissions_list'),
    url(r'^permissions/dispatch/$', views.dispatch_permission, name='permissions_dispatch'),

]

myCRM/rbac/models.py
from django.db import models


# Create your models here.

class Menu(models.Model):
    name = models.CharField(max_length=32, verbose_name='菜单标题')
    icon = models.CharField(max_length=32, null=True, blank=True)
    weight = models.IntegerField(default=100)  # 控制菜单排序的,权重值越大,菜单展示越靠前

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = verbose_name = '菜单'


class Role(models.Model):
    name = models.CharField(max_length=16)
    permissions = models.ManyToManyField('Permission')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = verbose_name = '角色'


class User(models.Model):
    # username = models.CharField(max_length=32)
    # password = models.CharField(max_length=32)
    roles = models.ManyToManyField(Role)

    class Meta:
        abstract = True


class Permission(models.Model):
    title = models.CharField(max_length=32, verbose_name='路由名称')
    url = models.CharField(max_length=32, verbose_name='url路由')
    menus = models.ForeignKey('Menu', null=True, blank=True, verbose_name='菜单')
    parent = models.ForeignKey('self', null=True, blank=True)
    url_name = models.CharField(max_length=32, null=True, blank=True)  # url的别名

    def __str__(self):
        return self.title

    class Meta:
        verbose_name_plural = verbose_name = '权限'

myCRM/rbac/views.py
from django.shortcuts import render, redirect, reverse, HttpResponse
from django.forms import modelformset_factory, formset_factory
from django.db.models import Q

from rbac.models import *
from rbac.forms import *
from rbac.utils.routers import get_all_url_dict

from sales.models import *

# Create your views here.


def role_list(request):
    role_list = Role.objects.all()
    context = {
        'role_list': role_list,
    }
    return render(request, 'role_list.html', context)


def role_add_edit(request, id=None):
    role_obj = Role.objects.filter(pk=id).first()
    if request.method == 'GET':
        role_form = RoleModelForm(instance=role_obj)
        return render(request, 'role_add_edit.html', {'role_form': role_form})
    else:
        role_form = RoleModelForm(request.POST, instance=role_obj)
        if role_form.is_valid():
            role_form.save()
            return redirect('rbac:role_list')
        else:
            return render(request, 'role_add_edit.html', {'role_form': role_form})


def role_del(request, id):
    Role.objects.filter(pk=id).delete()
    return redirect('rbac:role_list')


def menu_list(request):
    menu_id = request.GET.get('mid')
    menu_list = Menu.objects.all()

    if menu_id:
        permission_list = models.Permission.objects.filter(Q(menus_id=menu_id) | Q(parent__menus_id=menu_id)).values(
            'id', 'title', 'url', 'url_name', 'menus__id',
            'menus__name', 'menus__icon', 'parent_id')
    else:
        permission_list = Permission.objects.all().values('id', 'title', 'url', 'url_name', 'menus__id',
                                                                 'menus__name', 'menus__icon', 'parent_id')

    permission_dict = {}
    for permission in permission_list:
        pid = permission.get('menus__id')
        if pid:
            permission_dict[permission.get('id')] = permission
            permission_dict[permission.get('id')]['children'] = []
    # print(permission_dict)

    for p in permission_list:
        parent_id = p.get('parent_id')
        if parent_id:  # 1
            permission_dict[parent_id]['children'].append(p)

    return render(request, 'menu_list.html',
                  {'menu_list': menu_list, 'permission_list': permission_dict.values(), 'menu_id': menu_id})


def menu_add_edit(request, id=None):
    menu_obj = Menu.objects.filter(pk=id).first()
    if request.method == 'GET':
        menu_form = MenuModelForm(instance=menu_obj)
        return render(request, 'menu_add_edit.html', {'menu_form': menu_form})
    else:
        menu_form = MenuModelForm(request.POST, instance=menu_obj)
        if menu_form.is_valid():
            menu_form.save()
            return redirect('rbac:menu_list')
        else:
            return render(request, 'menu_add_edit.html', {'menu_form': menu_form})


def menu_del(request, id):
    models.Menu.objects.filter(pk=id).delete()
    return redirect('rbac:menu_list')


def permission(request, edit_id=None):
    permission_obj = Permission.objects.filter(id=edit_id).first()
    permission_form = PermissionForm(instance=permission_obj)
    if request.method == 'POST':
        permission_form = PermissionForm(request.POST, instance=permission_obj)
        if permission_form.is_valid():
            permission_form.save()
            return redirect(reverse('rbac:menu_list'))

    return render(request, 'menu_add_edit.html', {'menu_form': permission_form})


def del_permission(request, del_id):
    Permission.objects.filter(id=del_id).delete()
    return redirect(reverse('rbac:menu_list'))


def multi_permissions(request):
    """
    批量操作权限
    :param request:
    :return:
    """

    post_type = request.GET.get('type')

    # 更新和编辑用的
    FormSet = modelformset_factory(Permission, MultiPermissionForm, extra=0)
    # 增加用的
    AddFormSet = formset_factory(MultiPermissionForm, extra=0)

    permissions = Permission.objects.all()

    # 获取路由系统中所有URL
    router_dict = get_all_url_dict(ignore_namespace_list=['admin', ])

    # 数据库中的所有权限的别名
    permissions_name_set = set([i.url_name for i in permissions])

    # 路由系统中的所有权限的别名
    router_name_set = set(router_dict.keys())

    if request.method == 'POST' and post_type == 'add':
        add_formset = AddFormSet(request.POST)
        if add_formset.is_valid():
            permission_obj_list = [Permission(**i) for i in add_formset.cleaned_data]

            query_list = Permission.objects.bulk_create(permission_obj_list)

            for i in query_list:
                permissions_name_set.add(i.url_name)

    add_name_set = router_name_set - permissions_name_set
    add_formset = AddFormSet(initial=[row for name, row in router_dict.items() if name in add_name_set])

    del_name_set = permissions_name_set - router_name_set
    del_formset = FormSet(queryset=Permission.objects.filter(url_name__in=del_name_set))

    update_name_set = permissions_name_set & router_name_set
    update_formset = FormSet(queryset=Permission.objects.filter(url_name__in=update_name_set))

    if request.method == 'POST' and post_type == 'update':
        update_formset = FormSet(request.POST)
        if update_formset.is_valid():
            update_formset.save()
            update_formset = FormSet(queryset=Permission.objects.filter(url_name__in=update_name_set))

    return render(
        request,
        'multi_permissions.html',
        {
            'del_formset': del_formset,
            'update_formset': update_formset,
            'add_formset': add_formset,
        }
    )


def dispatch_permission(request):
    """
    分配权限
    :param request:
    :return:
    """

    uid = request.GET.get('uid')  # 1
    rid = request.GET.get('rid')  # 1

    if request.method == 'POST' and request.POST.get('postType') == 'role':
        user = UserInfo.objects.filter(id=uid).first()
        if not user:
            return HttpResponse('用户不存在')
        user.roles.set(request.POST.getlist('roles'))

    if request.method == 'POST' and request.POST.get('postType') == 'permission' and rid:
        role = Role.objects.filter(id=rid).first()
        if not role:
            return HttpResponse('角色不存在')
        role.permissions.set(request.POST.getlist('permissions'))

    # 查询所有用户
    user_list = UserInfo.objects.all()
    # 查询用户对应的id和角色
    user_has_roles = UserInfo.objects.filter(id=uid).values('id', 'roles')


    user_has_roles_dict = {item['roles']: None for item in user_has_roles}
    # {1:None,3:None}  #1和3是用户对应的角色id的值
    # if a in user_has_roles_dict:

    """
    用户拥有的角色id
    user_has_roles_dict = { 角色id：None }
    """
    # 获取所有角色
    role_list = Role.objects.all()

    if rid:
        role_has_permissions = Role.objects.filter(id=rid).values('id', 'permissions')
    elif uid and not rid:
        user = UserInfo.objects.filter(id=uid).first()
        if not user:
            return HttpResponse('用户不存在')
        role_has_permissions = user.roles.values('id', 'permissions')
    else:
        role_has_permissions = []
    # role_has_permissions 看用户所有角色对应的所有权限

    role_has_permissions_dict = {item['permissions']: None for item in role_has_permissions}

    """
    角色拥有的权限id
    role_has_permissions_dict = { 权限id：None }
    """

    all_menu_list = []  # 最终要做的数据结构就存在这里面

    queryset = Menu.objects.values('id', 'name')  # 一级菜单数据
    # queryset = [{'id':1,'name':'业务系统','children':[]},{'id':2,'name':'财务系统','children':[]}]

    menu_dict = {}
    '''
    menu_dict = {
        一级菜单id--1：{'id':1,'name':'业务系统','children':[
            {id:1,'title':'客户展示','menus_id':1,'children':[
                {'id':1,'title':'添加客户','parent_id':1},
                {'id':2,'title':'编辑客户','parent_id':1},
            ]},
            {id:2,'title':'缴费展示','menus_id':2,'children':[]},

        ]}，
        一级菜单id--2：{'id':2,'name':'财务系统','children':[]}，
        没有分配菜单的权限--None：{'id': None, 'name': '其他', 'children': []}
    }
    all_menu_list = [
        {'id':1,'name':'业务系统','children':[
            {id:1,'title':'客户展示','menus_id':1,'children':[
                {'id':1,'title':'添加客户','parent_id':1},
                {'id':2,'title':'编辑客户','parent_id':1},
            ]},
            {id:2,'title':'缴费展示','menus_id':2,'children':[]},
        ]},
        {'id':2,'name':'财务系统','children':[]},
        {'id': None, 'name': '其他', 'children': []}
    ]
    '''

    for item in queryset:
        item['children'] = []  # 放二级菜单，父权限
        menu_dict[item['id']] = item
        all_menu_list.append(item)

    other = {'id': None, 'name': '其他', 'children': []}
    all_menu_list.append(other)
    menu_dict[None] = other

    # 二级菜单权限数据
    root_permission = Permission.objects.filter(menus__isnull=False).values('id', 'title', 'menus_id')
    # [{id:1,'title':'客户展示','menus_id':1,'children':[]},{id:1,'title':'缴费展示','menus_id':2,'children':[]}]
    root_permission_dict = {}

    """
    root_permission_dict = {
        二级菜单id--1：{id:1,'title':'客户展示','menus_id':1,'children':[
            {'id':1,'title':'添加客户','parent_id':1},
            {'id':2,'title':'编辑客户','parent_id':1},
        ]},
        二级菜单id--2：{id:2,'title':'缴费展示','menus_id':2,'children':[]},

    }
    """

    for per in root_permission:
        per['children'] = []  # 放子权限
        nid = per['id']  # 二级菜单id值
        menu_id = per['menus_id']  # 一级菜单id值  -- 1
        root_permission_dict[nid] = per
        menu_dict[menu_id]['children'].append(per)

    # 二级菜单的子权限
    node_permission = Permission.objects.filter(menus__isnull=True).values('id', 'title', 'parent_id')
    # [{'id':1,'title':'添加客户','parent_id':1},{'id':2,'title':'编辑客户','parent_id':1},]
    for per in node_permission:
        pid = per['parent_id']  # pid 对应的二级菜单的id
        if not pid:
            menu_dict[None]['children'].append(per)
            continue
        root_permission_dict[pid]['children'].append(per)

    return render(
        request,
        'dispatch_permission.html',
        {
            'user_list': user_list,
            'role_list': role_list,

myCRM/rbac/templates/bread_crumb.html
{% for crumb in bread_crumb %}

    {% if forloop.last %}
        <li class="active">{{ crumb.title }}</li>
    {% else %}
        <li><a href="{{ crumb.url }}">{{ crumb.title }}</a></li>
    {% endif %}
{% endfor %}

myCRM/rbac/templates/menu.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
{% block custom_css %}
    <style>
        .left-menu .menu-body .static-menu .item .title {
            color:white;
        }

        .left-menu .menu-body .static-menu .icon-wrap {
            width: 20px;
            display: inline-block;
            text-align: center;
        }

        .left-menu .menu-body .static-menu a {
            text-decoration: none;
            padding: 8px 15px;
            border-bottom: 1px solid #ccc;
            color: #333;
            display: block;
            background: #efefef;
            background: -webkit-gradient(linear, left bottom, left top, color-stop(0, #efefef), color-stop(1, #fafafa));
            background: -ms-linear-gradient(bottom, #efefef, #fafafa);
            background: -moz-linear-gradient(center bottom, #efefef 0%, #fafafa 100%);
            background: -o-linear-gradient(bottom, #efefef, #fafafa);
            filter: progid:dximagetransform.microsoft.gradient(startColorStr='#e3e3e3', EndColorStr='#ffffff');
            -ms-filter: "progid:DXImageTransform.Microsoft.gradient(startColorStr='#fafafa',EndColorStr='#efefef')";
            box-shadow: inset 0px 1px 1px white;
        }

        .left-menu .menu-body .static-menu a:hover {
            color: #2F72AB;
            border-left: 2px solid #2F72AB;
        }

        .left-menu .menu-body .static-menu a.active {
            color: #2F72AB;
            border-left: 2px solid #2F72AB;
        }
    </style>
{% endblock custom_css %}
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

<div class="left-menu">
    <div class="menu-body">
        <div class="static-menu">
            {% for k,v in menu_order_dict.items %}
                <div class="item">
                    <div class="title"><i class="fa {{ v.icon }}"></i>{{ v.name }}</div>
                    <div class="body {{ v.class }}">
                        {% for child in v.children %}
                            <a href="{{ child.url }}" class="{{ child.class }}">{{ child.title }}</a>
                        {% endfor %}
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
</div>
<script src="{% static 'js/jquery-3.3.1.min.js' %} "></script>
<script src="{% static 'plugins/bootstrap/js/bootstrap.js' %} "></script>
{% block js %}
    <script>
        $('.title').click(function () {
            $(this).next().toggleClass('hidden');
        })
    </script>
{% endblock js %}

</body>
</html>

myCRM/rbac/templates/menu_add_edit.html
{% extends 'starter.html' %}
{% block custom_css %}
    <style>
       .luffy-container ul {
            list-style-type: none;
            padding: 0;
        }

        .luffy-container ul li {
            float: left;
            padding: 10px;
            padding-left: 0;
            width: 80px;
        }

        .luffy-container ul li i {
            font-size: 18px;
            margin-left: 5px;
            color: #6d6565;
        }

    </style>
{% endblock custom_css %}
{% block content %}
    <div class="luffy-container">
        <form class="form-horizontal clearfix" method="post" novalidate>
            {% csrf_token %}

            {% for field in menu_form %}
                <div class="form-group clearfix">
                    <label class="col-sm-2 control-label">{{ field.label }}</label>
                    <div class="col-sm-6">
                        {{ field }} <span style="color:firebrick;">{{ field.errors.0 }}</span>
                    </div>
                </div>
            {% endfor %}
            <div class="form-group col-sm-12">
                <div class="col-sm-6">
                    <div class="col-sm-offset-3">
                        <button type="submit" class="btn btn-primary">提 交</button>
                    </div>
                </div>
            </div>
        </form>
    </div>
{% endblock %}

myCRM/rbac/templates/menu_list.html
{% extends 'starter.html' %}

{% block css %}
    <style>
        .permission-area tr.parent {
            background-color: #cae7fd;;
        }

        .menu-body tr.active {
            background-color: #f1f7fd;
            border-left: 3px solid #fdc00f;
        }

        .active {
            background-color: #cae7fd;;
        }

    </style>
{% endblock %}


{% block content %}

    <div class="container-fluid">
        <div class="row">
            <div class="col-md-3">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h3 class="panel-title"><i class="fa fa-book"></i>菜单管理
                            <a href="{% url 'rbac:menu_add' %}" class="btn btn-success pull-right btn-sm"
                               style="padding: 1px 3px;color:white;">
                                <i class="fa fa-plus"></i>新建
                            </a>
                        </h3>
                    </div>
                    <div class="panel-body">
                        <table class="table table-bordered table-striped table-hover">
                            <thead>
                            <tr>
                                <th>名称</th>
                                <th>图标</th>
                                <th>操作</th>
                            </tr>
                            </thead>
                            <tbody class="menu-body">
                            {% for menu in menu_list %}

                                <tr class="{% if menu_id == menu.pk|safe %}active{% endif %}">
                                    <td><a href="">{{ menu.name }}</a></td>
                                    <td><i class="fa {{ menu.icon }}"></i></td>
                                    <td>
                                        <a href="{% url 'rbac:menu_edit' menu.pk %}"><i class="fa fa-edit"></i></a>
                                        <a href="{% url 'rbac:menu_del' menu.pk %}"><i class="fa fa-remove"></i></a>
                                    </td>
                                </tr>

                            {% endfor %}


                            </tbody>
                        </table>


                    </div>
                </div>

            </div>
            <div class="col-md-9">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h3 class="panel-title"><i class="fa fa-cubes"></i>权限管理
                            <a href="" class="btn btn-primary pull-right" style="padding: 1px 3px;color:white;">
                                <i class="fa fa-scissors"></i>批量操作</a>
                            <a href="" class="btn btn-success pull-right" style="padding: 1px 3px;color:white;">
                                <i class="fa fa-plus"></i>新建</a>
                        </h3>
                    </div>
                    <div class="panel-body">
                        <table class="table table-bordered table-hover permission-area">
                            <thead>
                            <tr>
                                <th>名称</th>
                                <th>URL</th>
                                <th>URL别名</th>
                                <th>菜单</th>
                                <th>所属菜单</th>
                                <th>操作</th>
                            </tr>
                            </thead>
                            <tbody>
                            {% for permission in permission_list %}

                                <tr class="parent {% if permission.menus__name %}active{% endif %}">

                                    <td class="click_caret"><i class="fa fa-caret-down icon"></i> {{ permission.title }}
                                    </td>
                                    <td>{{ permission.url }}</td>
                                    <td>{{ permission.url_name }}</td>
                                    <td>是</td>
                                    <td>{{ permission.menus__name }}</td>

                                    <td>
                                        <a href=""><i class="fa fa-edit"></i></a>
                                        <a href=""><i class="fa fa-remove"></i></a></td>
                                </tr>
                                {% for child_permission in permission.children %}
                                    <tr class="">

                                        <td>{{ child_permission.title }}</td>
                                        <td>{{ child_permission.url }}</td>
                                        <td>{{ child_permission.url_name }}</td>
                                        <td>

                                        </td>
                                        <td>{{ child_permission.menus|default:'' }}</td>

                                        <td>
                                            <a href=""><i class="fa fa-edit"></i></a>
                                            <a href=""><i class="fa fa-remove"></i></a></td>
                                    </tr>
                                {% endfor %}


                            {% endfor %}


                            </tbody>
                        </table>
                    </div>
                </div>

            </div>
        </div>

    </div>



{% endblock %}


{% block js %}
    <script>
        $('.click_caret').click(function () {
            $(this).parent().find('.icon').toggleClass('fa-caret-right');
            $(this).parent().nextUntil('.parent').toggleClass('hidden');
        })

    </script>

{% endblock %}

myCRM/rbac/templates/multi_permissions.html
{% extends 'starter.html' %}

{% block content %}
    <div class="luffy-container">
        <form method="post" action="?type=add">
            {% csrf_token %}
            {{ add_formset.management_form }}
            <div class="panel panel-default">
                <!-- Default panel contents -->
                <div class="panel-heading">
                    <i class="fa fa-binoculars" aria-hidden="true"></i> 待新建权限列表
                    <button class="right btn btn-primary btn-xs" style="padding: 2px 8px;margin: -3px;">
                        <i class="fa fa-save" aria-hidden="true"></i>
                        新建
                    </button>
                </div>
                <div class="panel-body" style="color: #9d9d9d;">
                    注意：路由系统中自动发现且数据库中不存在的路由。
                </div>

                <table class="table table-bordered">
                    <thead>
                    <tr>
                        <th>序号</th>
                        <th>名称</th>
                        <th>URL</th>
                        <th>别名</th>
                        <th>所属菜单</th>
                        <th>根权限</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for form in add_formset %}

                        <tr>
                            <td style="vertical-align: middle;">{{ forloop.counter }}</td>
                            <td>{{ form.title }} <span>{{ form.title.errors.0 }}</span></td>
                            <td>{{ form.url }}</td>
                            <td>{{ form.url_name }}</td>
                            <td>{{ form.parent }}</td>
                            <td>{{ form.menus }}</td>

                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </form>

        <div class="panel panel-default">
            <!-- Default panel contents -->
            <div class="panel-heading">
                <i class="fa fa-th-list" aria-hidden="true"></i> 待删除权限列表
            </div>
            <div class="panel-body" style="color: #9d9d9d;">
                注意：数据库中存在，但路由系统中不存在的路由。
            </div>

            <table class="table table-bordered">
                <thead>
                <tr>
                    <th>序号</th>
                    <th>名称</th>
                    <th>URL</th>
                    <th>别名</th>
                    <th>父权限</th>
                    <th>所属菜单</th>
                    <th>操作</th>
                </tr>
                </thead>
                <tbody>
                {% for form in del_formset %}

                    <tr>
                        {{ form.id }}

                        <td style="vertical-align: middle;">{{ forloop.counter }}</td>
                        <td>{{ form.title }} <span>{{ form.title.errors.0 }}</span></td>
                        <td>{{ form.url }}</td>
                        <td>{{ form.url_name }}</td>
                        <td>{{ form.parent }}</td>
                        <td>{{ form.menus }}</td>
                        <td>
                            <a href="{% url 'rbac:permission_del' form.id.value %}" style="color:#d9534f;">
                                <i class="fa fa-trash-o" aria-hidden="true"></i>
                            </a>
                        </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>

        <form method="post" action="?type=update">
            {% csrf_token %}
            {{ update_formset.management_form }}
            <div class="panel panel-default">
                <!-- Default panel contents -->
                <div class="panel-heading">
                    <i class="fa fa-sitemap" aria-hidden="true"></i> 待更新权限列表
                    <button class="right btn btn-primary btn-xs" style="padding: 2px 8px;margin: -3px;">
                        <i class="fa fa-save" aria-hidden="true"></i>
                        更新
                    </button>
                </div>
                <div class="panel-body" style="color: #9d9d9d;">
                    注意：数据库和路由系统都存在的路由。
                </div>

                <table class="table table-bordered">
                    <thead>
                    <tr>
                        <th>序号</th>
                        <th>名称</th>
                        <th>URL</th>
                        <th>别名</th>
                        <th>父权限</th>
                        <th>所属菜单</th>
                        <th>操作</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for form in update_formset %}
                        <tr>
                            {{ form.id }}

                            <td style="vertical-align: middle;">{{ forloop.counter }}</td>
                            <td>{{ form.title }} <span>{{ form.title.errors.0 }}</span></td>
                            <td>{{ form.url }}</td>
                            <td>{{ form.url_name }}</td>
                            <td>{{ form.parent }}</td>
                            <td>{{ form.menus }}</td>
                            <td>
                                <a href="{% url 'rbac:permission_del' form.id.value %}" style="color:#d9534f;">
                                    <i class="fa fa-trash-o" aria-hidden="true"></i>
                                </a>
                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </form>
    </div>
{% endblock %}

myCRM/rbac/templates/role_add_edit.html
{% extends 'starter.html' %}

{% block content %}
    <div class="luffy-container">
        <form class="form-horizontal clearfix" method="post" novalidate>
            {% csrf_token %}

            {% for field in role_form %}
                <div class="form-group clearfix">
                    <label class="col-sm-2 control-label">{{ field.label }}</label>
                    <div class="col-sm-6">
                        {{ field }} <span style="color:firebrick;">{{ field.errors.0 }}</span>
                    </div>
                </div>
            {% endfor %}
            <div class="form-group col-sm-12">
                <div class="col-sm-6">
                    <div class="col-sm-offset-3">
                        <button type="submit" class="btn btn-primary">提 交</button>
                    </div>
                </div>
            </div>
        </form>
    </div>
{% endblock %}

myCRM/rbac/templates/role_list.html
{% extends 'starter.html' %}

{% block content %}

    <div class="luffy-container">
        <div class="btn-group" style="margin: 5px 0">
            <a class="btn btn-default" href="{% url 'rbac:role_add' %}">
                <i class="fa fa-plus-square" aria-hidden="true"></i> 添加角色
            </a>
        </div>
        <table class="table table-bordered table-hover">
            <thead>
            <tr>
                <th>序号</th>
                <th>角色</th>

                <th>选项</th>
            </tr>
            </thead>
            <tbody>
            {% for role in role_list %}
                <tr>
                    <td>{{ role.id }}</td>
                    <td>{{ role.name }}</td>

                    <td>
                        <a style="color: #333333;" href="{% url 'rbac:role_edit' role.id %}">
                            <i class="fa fa-edit" aria-hidden="true"></i></a>
                        |
                        <a style="color: #d9534f;" href="{% url 'rbac:role_del' role.id %}"><i class="fa fa-trash-o"></i></a>
                    </td>

                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock %}